build:
  main: main.go
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - 386

archive:
  format: tgz
  replacements:
    amd64: 64-bit
    darwin: macos
  files:
    - readme.md
    - license

checksum:
  name_template: "{{ .ProjectName }}_checksum.txt"
    
release:
  draft: true